apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kam
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: kam
    app.kubernetes.io/name: kam
    app.kubernetes.io/part-of: kam
    app.openshift.io/runtime: go
  name: kam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kam
  template:
    metadata:
      labels:
        app: kam
    spec:
      containers:
      - name: kam
        imagePullPolicy: Always
        image: quay.io/isequeir/kam:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5