apiVersion: v1
kind: Service
metadata:
  labels:
    app: kam
  name: kam
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: kam
  sessionAffinity: None
  type: ClusterIP