  
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kam
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/ishitasequeira/kamApps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true